# Required git and bash-completion

if [ "$PS1" ]; then
  # Uncomment if need it
  # Archlinux
  # [ -r /usr/share/git/completion/git-prompt.sh ] && . /usr/share/git/completion/git-prompt.sh
  # CentOS
  # [ -r /etc/bash_completion.d/git ] && . /etc/bash_completion.d/git 
  PS1='\[\033[01;32m\][\u@\h \[\033[01;34m\]\W\[\033[01;33m\]$(__git_ps1 " git:%s")\[\033[01;32m\]]\$\[\033[00m\] '
  if [ "$(id -u)" = "0" ]; then
    PS1=${PS1//32m/31m};
  fi
fi

