# Required git and bash-completion

if [ "$PS1" ]; then
  # Uncomment if need it
  # Archlinux
  # [ -r /usr/share/git/completion/git-prompt.sh ] && . /usr/share/git/completion/git-prompt.sh
  # CentOS
  # [ -r /etc/bash_completion.d/git ] && . /etc/bash_completion.d/git 
  PS1='\[\033[01;32m\][\u@\h \[\033[01;34m\]\W\[\033[01;33m\]$(__git_ps1 " git:%s")\[\033[01;32m\]]\$\[\033[00m\] '
  if [ "$(id -u)" = "0" ]; then
    PS1=${PS1//32m/31m};
  fi
fi


# Wireguard peers name (example: PublicKey {KEY} # Peer name)
function wg {
    WG_COLOR_MODE=always command wg "$@" | sed -e "$(while read -r tag eq key hash name; do [ "$tag" == "PublicKey" ] && echo "s#$key#$key ($name)#;"; done < /etc/wireguard/wg0.conf)"
}
